{% set name = "karn" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prydonius/karn/archive/v{{ version }}.tar.gz
  sha256: 96f10ff263468b9f91244edf16d8ea548c9d281cba9b2597eaf5270f9e6127e3

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - karn --help

about:
  home: https://github.com/karn/karn
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage multiple Git identities
  dev_url: https://github.com/karn/karn

extra:
  recipe-maintainers:
    - danielnachun
